### ISSUE TITLE
Update Email Templates UI

### ISSUE THREAD

**Issue by xgp** [p2-inc/keycloak-ui#11]
The goal is to give an admin user (i.e. user of the Keycloak Admin UI) the ability to set their email templates in the admin UI. The format of the templates will be mustache, and they will be stored in realm attributes. We have/are building some specific methods to enable this interface. This work is gated by the completion of https://github.com/p2-inc/keycloak-themes/issues/2

This will be a new "Emails" tab in the "Extensions" -> "Styles" portion of the admin ui. 

### Heading
- Title: "Emails"
- Subtitle: "Use these templates to override the default content of your emails. [Configure email server settings](/auth/admin/master/console/#/test/realm-settings/email).
- Optional warning (if the `realm.emailTheme` is not set to `attributes`): Your email theme must be set to `attributes` for these changes to take effect  [Configure email theme settings](/auth/admin/master/console/#/test/realm-settings/themes).
- Documentation link: https://phasetwo.io/docs/getting-started/email

### Form
- **Template type**: dropdown populated from `GET /auth/realms/{realm}/emails/templates` (returns a hash of `templateName` -> `templateDescription`)
    - Dropdown options should be formatted `{templateDescription} ({templateName})`
    - Selecting the dropdown value populates the textareas below
- **HTML template**: textarea populated from `GET /auth/realms/{realm}/emails/templates/html/{templateName}`
- **Text template**: textarea populated from `GET /auth/realms/{realm}/emails/templates/text/{templateName}`
- **Save**: button that saves the currently selected template with two update methods
    - `PUT /auth/realms/{realm}/emails/templates/html/{templateName}` for the html template
    - `PUT /auth/realms/{realm}/emails/templates/text/{templateName}` for the text template
- **Cancel**: button reverts the textareas to the original values

**Comment by xgp** [comment]
https://github.com/p2-inc/keycloak-themes/issues/2 is done, and the methods above are now available.

**Comment by pnzrr** [comment]
@xgp I'm hitting Access Control (CORS) issues for the endpoints above. Can you tweak the API to allow localhost access? Also the `/templates/templateType/templateName` route is throwing a 406 error and I can't figure out what type of Accepts header it seems to want. Can you advise?

**Comment by xgp** [comment]
@pnzrr The CORS issue should be fixed. Hit it again and let me know if you see the same problem. 

Regarding the 406, can you send me the full request so I can try to reproduce?

**Comment by pnzrr** [comment]
```
curl 'https://app.phasetwo.io/auth/realms/adminui/emails/templates/html/email-verification' \
  -H 'authority: app.phasetwo.io' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'authorization: Bearer ....' \
  -H 'cache-control: no-cache' \
  -H 'origin: http://localhost:8081' \
  -H 'pragma: no-cache' \
  -H 'referer: http://localhost:8081/' \
  -H 'sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' \
  --compressed
```

**Comment by pnzrr** [comment]
```
fetch("https://app.phasetwo.io/auth/realms/adminui/emails/templates/text/email-verification", {
  "headers": {
    "accept": "application/json",
    "accept-language": "en-US,en;q=0.9",
    "authorization": "Bearer ...",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "sec-ch-ua": "\"Not?A_Brand\";v=\"8\", \"Chromium\";v=\"108\", \"Google Chrome\";v=\"108\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrer": "http://localhost:8081/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "include"
});
```

**Comment by pnzrr** [comment]
Super close, but the `PUT` for saving is failing with a 500 response code. Is there an issue with how I'm submitting the response? Or with how the server is reading it? 

```
curl 'https://app.phasetwo.io/auth/realms/adminui/emails/templates/text/email-update-confirmation' \
  -X 'PUT' \
  -H 'authority: app.phasetwo.io' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'authorization: Bearer ...' \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data' \
  -H 'origin: http://localhost:8081' \
  -H 'pragma: no-cache' \
  -H 'referer: http://localhost:8081/' \
  --data-raw $'------WebKitFormBoundarywuvWAlHBXMcBfu9l\r\nContent-Disposition: form-data; name="template"\r\n\r\nTo update your {{realmName}} account with email address {{newEmail}}, click the link below\r\n\r\n{{link}}\r\n\r\nThis link will expire within {{#linkExpirationFormatter}}{{linkExpiration}}{{/linkExpirationFormatter}}.\r\n\r\nIf you don\'t want to proceed with this modification, just ignore this message.\r\n\r\n------WebKitFormBoundarywuvWAlHBXMcBfu9l--\r\n' \
  --compressed
```

**Comment by pnzrr** [comment]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/93841792/211449073-91430e99-8dea-4b79-89ec-73a022f257fe.png">
<img width="417" alt="image" src="https://user-images.githubusercontent.com/93841792/211449108-f175d49a-45c2-492c-9f6e-54319ebafd61.png">

**Comment by xgp** [comment]
That request looks like it's missing the `boundary` specification in the content type. The way those `multipart/form-data` requests work is that the content type header has to tell the server how to parse the boundaries of the "parts". A correct header in your example will look like this:
```
content-type: multipart/form-data; boundary=------WebKitFormBoundarywuvWAlHBXMcBfu9l
```

**Comment by xgp** [comment]
Update for UX
1. in warning have "Activate" button that saves the realm with `realm.emailTheme = attributes`
2. have the dropdown inactive unless the email theme is set to `attributes`


![Image](https://user-images.githubusercontent.com/244253/212758354-805cbdff-fb57-4972-9718-9d2b263bf81f.png)

**Comment by pnzrr** [comment]
Updated. 

![Image](https://user-images.githubusercontent.com/93841792/213078942-47ee1180-9114-41ed-b31a-65f0686391f3.png)



![Image](https://user-images.githubusercontent.com/93841792/213078992-ea23daf6-91b4-4c9c-bf7d-b16dd8cc159b.png)

**Comment by pnzrr** [comment]
![Image](https://user-images.githubusercontent.com/93841792/213079072-d99b1d26-62c4-4cf0-82e1-36efe0c36156.png)

**Comment by pnzrr** [comment]
#17
