### ISSUE TITLE
Allow IDP selection per org

### ISSUE THREAD

**Issue by xgp** [p2-inc/keycloak-ui#2]
```
    idp.config["syncMode", "FORCE"];
    idp.config["hideOnLoginPage", "true"];
    idp.config["home.idp.discovery.org", organization.id];
    idp.postBrokerLoginFlowAlias​ = "post org broker login");
```

**Comment by xgp** [comment]
- Add an "Identity Providers" tab to the organization page

When that tab is selected, it should
- show an Identity Provider detail (displayName and alias) with the heading "Organization owned IdP" if it has one
  - you can detect if it has one by looking in the IdP config for it's organization ID with key `home.idp.discovery.org`
- show a dropdown with all IdentityProviders. the names in the list should be `${displayName} (${alias}) - ${org.displayName)`
  - the ` - ${org.displayName)` part is only populated if the `home.idp.discovery.org` key exists in the config
- show a "Save" and "Cancel" button 
  - Save sets the parameters above and saves the idp
  - Cancel resets the form

**Comment by jeffpatzer** [comment]
- What's the right way to assign an IdP to these orgs for testing? None of my test ones have them. I need to get some sample ones pulled in for building out. 
- I assume this should be a form that allows one to edit the `displayName and the `alias`?
- Auto select the first IdP available? Or should it be empty then you have to chose the IdP via a drop down?


Current page stub with lots of plumbing once I know about the data piece. 
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/178291/204709899-60d8fd2c-6143-4e00-a333-e4c31a168fd2.png">

**Comment by xgp** [comment]
This is looking great. A few comments.

### The way to find an organization's active IdP:
1. Query all IdP's for a realm using `GET /{realm}/identity-provider/instances` 
2. See if there is one with the organization's ID in the `config->home.idp.discovery.org` field of the IdP
3. Verify that the IdP has `enabled=true`

### In this UI, if the organization has an active IdP:
1. Show a line (not editable) indicating "Active Identity Provider: <display-name> (<alias>)

### In a dropdown below that line
1. Use all IdPs from the query above
2. Filter out the active one for this organization, if it exists
3. Filter out any IdPs that have an organization's ID in the `config->home.idp.discovery.org` field of the IdP that **does not** match this organization's
4. If the user selects one of the IdPs, activate the "Save" and "Cancel" buttons

### The side effect of selecting a new/different IdP and saving is:
1. If the organization already has an active IdP per above, set that IdP to `enabled=false` and update using `PUT /{realm}/identity-provider/instances/{alias}`
2. Set the following fields on the new/different IdP and update with `PUT /{realm}/identity-provider/instances/{alias}`
```
    idp.config["syncMode", "FORCE"];
    idp.config["hideOnLoginPage", "true"];
    idp.config["home.idp.discovery.org", organization.id];
    idp.postBrokerLoginFlowAlias​ = "post org broker login");
```
3. Refresh the screen to show the updated active IdP and dropdown.

**Comment by xgp** [comment]
To answer your questions directly:

> What's the right way to assign an IdP to these orgs for testing? None of my test ones have them. I need to get some sample ones pulled in for building out.

See the above for saving an IdP. 

> I assume this should be a form that allows one to edit the displayName and the alias`?

No. It is display only. You can't edit them in this screen.

> Auto` select the first IdP available? Or should it be empty then you have to chose the IdP via a drop down?

Empty first.

**Comment by pnzrr** [comment]
Got it, thanks for the thorough explanation. I was pulling from this endpoint which was returning an empty array `https://phasetwo.io/api/get-identity-providers-for-this-organization`. I'll pull it via the other endpoint.

**Comment by jeffpatzer** [comment]
I'm getting a CORS error with the endpoint `GET /{realm}/identity-provider/instances`

Trying to access the identity providers via the `adminClient` object also isn't working as that just returns an empty array. 

```
fetch("https://app.phasetwo.io/auth/realms/adminui/identity-provider/instances", {
  "headers": {
    "accept": "application/json",
    "authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJPaDJqc3ZVTFFOWkhkaDFWVlU5UWFfSDVWQjdNeXhNQ1M0blh3UkJjWHNvIn0.eyJleHAiOjE2Njk4Njc5NTIsImlhdCI6MTY2OTg2Nzg5MiwiYXV0aF90aW1lIjoxNjY5Nzc3NTM1LCJqdGkiOiIyMzAzMzA1Ni1lMGMxLTRkM2QtODM3MC0zOTFkNTdiY2VkMDIiLCJpc3MiOiJodHRwczovL2FwcC5waGFzZXR3by5pby9hdXRoL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOlsiYWRtaW51aS1yZWFsbSIsImFjY291bnQiXSwic3ViIjoiYjdhYjYyZWQtNWYxNC00YzcyLTkyYmEtYmM3ZWE0NDQ2MGZlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoic2VjdXJpdHktYWRtaW4tY29uc29sZS12MiIsIm5vbmNlIjoiM2M2OTM3NzEtZTk4MC00ODRlLTg5ZGItZjNkOGU5YmM1ZThhIiwic2Vzc2lvbl9zdGF0ZSI6ImVmMGFjMGZjLThhYjctNGFhZC1iOTliLTY4NTc2MWY3ZWY3MiIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vbG9jYWxob3N0OjgwODEiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtbWFzdGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFkbWludWktcmVhbG0iOnsicm9sZXMiOlsidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJ2aWV3LXJlYWxtIiwibWFuYWdlLW9yZ2FuaXphdGlvbnMiLCJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwiaW1wZXJzb25hdGlvbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJwdWJsaXNoLWV2ZW50cyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LW9yZ2FuaXphdGlvbnMiLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiZWYwYWMwZmMtOGFiNy00YWFkLWI5OWItNjg1NzYxZjdlZjcyIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJKZWZmIFBhdHplciIsInByZWZlcnJlZF91c2VybmFtZSI6ImpwYXR6ZXJAZ21haWwuY29tIiwiZ2l2ZW5fbmFtZSI6IkplZmYiLCJmYW1pbHlfbmFtZSI6IlBhdHplciIsImVtYWlsIjoianBhdHplckBnbWFpbC5jb20ifQ.BPn043g9IW0gKfhTx4lT75TkNkigM467PguJSWy1ooWI25r263u5MHS-JI-4Txnwad5la-RRM-kekMlV36nI49iy1R-y0r9Zbtze4rtiV97a1u_MOhgxNVQ_DvuObydLj0NevDn0JX9zr10pPOrTWh8FfAh2bpydkm_wpGsNKceAXcMr99_geH--6jNWjlCg93z__qmaRTqaggu2FQNHYicjdMN7IUSZO6cHDb94gKd0HGP3cuc35ysQowdlxlvwf_Z-5p19YKKoFkrBuD-p14I5drXC8MJ74sE1BpvvF9KciXkFpQ94E0x4KTb4x9zx21-nDB402Qb-pOJ2mg3fow",
    "sec-ch-ua": "\"Google Chrome\";v=\"107\", \"Chromium\";v=\"107\", \"Not=A?Brand\";v=\"24\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\""
  },
  "referrer": "http://localhost:8081/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "include"
});
```

<img width="672" alt="image" src="https://user-images.githubusercontent.com/178291/204964097-cd639909-a12e-4ea1-b7c5-35420e9012a2.png">

**Comment by xgp** [comment]
@pnzrr Using the identity providers via the `adminClient` object is the right thing to do. It was returning empty because there were no IdPs. I added 6 stubs that show up when you query now.

**Comment by jeffpatzer** [comment]
@xgp still seeing empty arrays when i check that adminClient `identityProviders`. I checked each org and they all do. What am I doing wrong here to get them to show up? 

<img width="1624" alt="Screenshot 2022-12-02 at 7 58 35 PM" src="https://user-images.githubusercontent.com/178291/205419271-dac31fe2-43b8-40ca-9443-25068eb6eaa4.png">

**Comment by xgp** [comment]
In order to populate the dropdown, you must get **all** IdPs for the realm, which is independent of the org.
    a. using the admin client like this `kcAdminClient.identityProviders.find();`
    b. which should produce a request like this
```
curl 'https://app.phasetwo.io/auth/admin/realms/cloud/identity-provider/instances' \
  -H 'authority: app.phasetwo.io' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'authorization: bearer eyJhb....6B0iw' \
  -H 'origin: http://localhost:8081' \
  -H 'referer: http://localhost:8081/' \
```

Let me know if you are still seeing empty, and we can get on a zoom to sort it out.

**Comment by pnzrr** [comment]
That fixed querying it, but looks like the object is still coming up empty 😢 

<img width="2022" alt="Screenshot 2022-12-03 at 5 02 14 PM" src="https://user-images.githubusercontent.com/93841792/205467422-d1561107-a6a4-49e4-9836-44b19971f889.png">

**Comment by xgp** [comment]
Yeah. That's because I added the test ones to the `cloud` realm. I added some to the `adminui` realm too just now. If you need to add/change them, nav to the Identity Providers section and do it there. You can set them up with garbage data. Let me know if I can help with that.

**Comment by pnzrr** [comment]
Ok, seeing them now. My localhost version doesn't seem to like the cloud login I've got. Only the `admin-ui` one.

**Comment by pnzrr** [comment]
Almost there. Just getting a 500 for the API call to update. 

<img width="733" alt="image" src="https://user-images.githubusercontent.com/93841792/205813969-ee1967cc-a85e-4f48-a0cc-ed293e0c45bc.png">


Also, just making sure, the newly selected IDP should be have `enabled=true` toggled as well?

**Comment by xgp** [comment]
This is 2 problems. 
1. need to update the update method you're using (see my comment in the PR)
2. the `post org broker login` wasn't yet created in the adminui realm. (i'll take care of that)

**Comment by xgp** [comment]
I added a `post org broker login` flow to the `adminui` realm.

**Comment by pnzrr** [comment]
Got it. PR is updated. Getting a CORs error for local, but imagine that will be ok to be able to test once enabled.
