### ISSUE TITLE
Portal Link not accessable in self-hosted version

### ISSUE THREAD

**Issue by paulwer** [p2-inc/keycloak-ui#29]
Hey everyone,
I just self-deployed your docker image, but run into trouble, when wanting to generate a portal-link.
The api-response is: `portal-link is only supported in paid Phase Two distributions`

is this a bug, wrong configuration or a limitation to the open-source self hosted version?

**Comment by xgp** [comment]
Hi @paulwer thanks for the message. It depends on which "portal" link you are referring to. 
- the "portal link" that is created in the admin UI that opens a session to allow configuring a IdP on behalf of an organization using the wizard, then this is only available as a licensed extension, and is not available in the open source version.
- the "admin portal" that allows your users to self-manage their organizations and profile is available as open source (https://github.com/p2-inc/phasetwo-admin-portal) and can be accessed by a logged in user at `https://{host}/{relative-path}/realms/{realm}/portal/`

**Comment by paulwer** [comment]
@xgp thank you for your message.
I was refering to your first point. I guess it would be more suiteable to show the user within the portal that he cannot create the link. right now there is just an empty link-box and no informations.
(I had to look it up myself with the browser console)

**Comment by xgp** [comment]
@paulwer Great suggestion. Sorry that wasn't clear.
