### ISSUE TITLE
Way to upload/set css and logo

### ISSUE THREAD

**Issue by xgp** [p2-inc/keycloak-ui#4]
New section in the "Extensions" section called "Styles"

Opens a page with 
Header: Styles
Sub header: Customize the look and feel of your login, user management, organization portal and emails. 
Link: TBD

2 tabs
1. titled "General"
Form with
- Logo URL: input box
  - shows preview, bounded size, after save
- Favicon URL: input box
  - shows preview, bounded size, after save
- Save/Cancel button

2. titled "Login"
Form with:
- Primary color: input box 
  - validates it's a html hex color
  - shows preview of the color, after save
- Secondary color: input box 
  - validates it's a html hex color
  - shows preview of the color, after save
- Background color: input box 
  - validates it's a html hex color
  - shows preview of the color, after save
- CSS override: textarea
  - Note: This will override any changes to colors above.
- Save/Cancel button

Both forms set the realm attributes, using the keys below. Realm attributes are set by loading the realm, updating the `attributes` and calling a PUT to update. You can also use the Realm Attributes API https://phasetwo.io/api/get-realm-attributes if you want to avoid bulk changes.

Realm attribute names:
```
_providerConfig.assets.login.css
_providerConfig.assets.login.primaryColor
_providerConfig.assets.login.secondaryColor
_providerConfig.assets.login.backgroundColor
_providerConfig.assets.logo.url
_providerConfig.assets.favicon.url
```

- validate the CSS and images?
- import CSS from url?

**Comment by xgp** [comment]
New section in the "Extensions" section called "Styles"

Opens a page with 
Header: Styles
Sub header: Customize the look and feel of your login, user management, organization portal and emails. 
Link: TBD

2 tabs
1. titled "General"
Form with
- Logo URL: input box 
  - shows preview, bounded size, after save
- Favicon URL: input box
  - shows preview, bounded size, after save
- Save/Cancel button

2. titled "Login"
Form with:
- Primary color: input box 
  - validates it's a html hex color
  - shows preview of the color, after save
- Secondary color: input box 
  - validates it's a html hex color
  - shows preview of the color, after save
- CSS override: textarea
- Save/Cancel button

Both forms set the realm attributes, using the keys above. Realm attributes are set by loading the realm, updating the `attributes` and calling a PUT to update.

**Comment by xgp** [comment]
I'd like to generate a palette based on 1-2 colors. Do you know of any tools that do this?

**Comment by pnzrr** [comment]
For the 

>CSS override: textarea
>. Note: This will override any changes to colors above.

How will one know what classes they could possibly override? In the text boxes, that is a bounded value, but this could possibly be anything. Just not clear how you imagine the interplay with those and the bounded items.

**Comment by xgp** [comment]
How appsmith does their branding page.

![Image](https://user-images.githubusercontent.com/244253/206691406-b0ee1bb9-0b5a-4518-9e9f-15cc69c704aa.png)

**Comment by xgp** [comment]
@pnzrr 2 things
1. the `_providerConfig.` prefix to the attributes needs to be there, so I added it back.
2. we shouldn't set attributes for empty values. E.g. if the user doesn't fill in the CSS field on the *Login* tab, don't set a value for the `_providerConfig.assets.login.css`

**Comment by pnzrr** [comment]
I think this one is done.
