### ISSUE TITLE
Realm Attributes UI

### ISSUE THREAD

**Issue by xgp** [p2-inc/keycloak-ui#9]
New section in the "Extensions" section called "Attributes"

Opens a page with
Header: Attributes
Sub header: Danger: Expert mode customization for Phase two extensions. This may override configuration changes elsewhere, and cause unexpected behavior. Use this only if you are sure what you are doing. (Red?)
Link: TBD

Table with Key, Value header
- Each row has a text input for name and value, minus for delete
- Can add attribute
- Save/Revert buttons at bottom
(See User/Attribute UI for example)
![image](https://user-images.githubusercontent.com/244253/202762560-a968c734-e2c0-4fc4-b9ea-b8a8f036b656.png)

Use the Realm Attributes API:
- https://phasetwo.io/api/get-realm-attributes
- Only display attributes with `_providerConfig.` prefix
- Order by alphabetical

**Comment by xgp** [comment]
@pnzrr Putting this on hold pending this https://github.com/keycloak/keycloak-ui/pull/4046
It might be done for us, and make it into keycloak main. In a few days, I'll make a go/no-go. Either way, the code is done for us.

**Comment by pnzrr** [comment]
Looks like they are still reviewing it. I am going to assume that it's still on hold.

**Comment by xgp** [comment]
@pnzrr The KC maintainer weighed in, and this won't get merged https://github.com/keycloak/keycloak-ui/pull/4046#issuecomment-1372204214 (probably because I commented on it).

Let's pull the code and use it for our own in the "Extensions" section, "Attributes" tab, as defined above.

**Comment by xgp** [comment]
@pnzrr I merged in the changes from the upstream pr. It still needs warning, filter on `_providerConfig` prefix and sorting. I'm okay with having it in the Realm Settings section, as it should probably live there anyway.

**Comment by pnzrr** [comment]
![Image](https://user-images.githubusercontent.com/93841792/213083381-2c8d9579-7ef2-4945-8cf6-40149519739e.png)

**Comment by pnzrr** [comment]
Should be ready
